services:
  genesis-generator:
    image: hyperledger/besu:24.8.0
    user: "0"
    volumes:
      - ./qbftConfigFile.json:/config/config.json:ro
      - ./networkFiles:/workspace/networkFiles
    working_dir: /workspace
    command: >
      besu operator generate-blockchain-config
      --config-file=/config/config.json
      --to=/workspace/networkFiles
      --private-key-file-name=key
    profiles:
      - gen
